version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    networks:
      - app-tier
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
  kafka-producer:
    image: stantr01/kafka-producer:1.2
    networks:
      - app-tier
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAKFA_TOPIC=stock
  kafka-consumer:
    image: stantr01/kafka-consumer:1.5
    networks:
      - app-tier
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=stock
      - KAFKA_TOPIC=stock

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
